title: Gervásio Júnior
url: "https://gervasiocaj.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

#gems:
# - jekyll-paginate
# - jekyll-admin

#paginate: 10
#paginate_path: /blog/page/:num/
permalink: none

timezone: America/Fortaleza

sass:
    style: compressed
    sass_dir: _sass
